# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: clone termux-app repo
        run: git clone https://github.com/termux/termux-app
        
        
      - name: create test packages
        run: |
          mkdir -p termux-app/app/build/outputs/apk/debug
          cd termux-app/app/build/outputs/apk/debug
          touch app-universal-debug.apk app-arm64-v8a-debug.apk app-armeabi-v7a-debug.apk app-x86_64-debug.apk app-x86-debug.apk
        
      - name: Rename files
        run: |
          remote_version=$(cat termux-app/app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
          echo "lastest version: $remote_version"
          cd termux-app/app/build/outputs/apk/debug
          for var in $(ls)
          do
            if [ ${var##*.} == "apk" ];then
               mv -f "$var" $(echo "$var"|sed 's/app/termux-app/' |sed 's/-debug/'_${remote_version}/)
            fi
          done
          echo result of rename
          echo current dir is
          pwd
          ls
          
#       - name: Store generated universal APK file
        # uses: actions/upload-artifact@v2
        # with:
        #   name: termux-app-universal
        #   path: |
        #       ./termux-app/app/build/outputs/apk/debug/termux-app-universal_${{remote_version}}.apk
        #       .termux-app/app/build/outputs/apk/debug/output-metadata.json
#
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello-world"
   
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}}      
